
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author csa
 */
public class Ser extends javax.swing.JFrame {

    /**
     * Creates new form Ser
     */
    public Ser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        EnterPButton = new javax.swing.JButton();
        ModifyPButton = new javax.swing.JButton();
        BackRButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 0, 204))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(680, 380));

        EnterPButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        EnterPButton.setText("Same Date  (F11)");
        EnterPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterPButtonActionPerformed(evt);
            }
        });
        EnterPButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterPButtonKeyPressed(evt);
            }
        });

        ModifyPButton.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        ModifyPButton.setText("Previous Date  (F12)");
        ModifyPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyPButtonActionPerformed(evt);
            }
        });
        ModifyPButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModifyPButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(EnterPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(ModifyPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnterPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        BackRButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        BackRButton.setText("Back");
        BackRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackRButtonActionPerformed(evt);
            }
        });
        BackRButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BackRButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterPButtonActionPerformed
        this.setVisible(false);
        ShowSpecserv s = new ShowSpecserv();
        s.setVisible(true);
    }//GEN-LAST:event_EnterPButtonActionPerformed

    private void EnterPButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnterPButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.setVisible(false);
            new MainMenu().setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F11){
            this.setVisible(false);
        ShowSpecserv s = new ShowSpecserv();
        s.setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F12){
            this.setVisible(false);
            Show s = new Show();
            s.setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_RIGHT){
            ModifyPButton.requestFocus();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.setVisible(false);
        ShowSpecserv s = new ShowSpecserv();
        s.setVisible(true);
        }
    }//GEN-LAST:event_EnterPButtonKeyPressed

    private void ModifyPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyPButtonActionPerformed
       this.setVisible(false);
            Show s = new Show();
            s.setVisible(true);
    }//GEN-LAST:event_ModifyPButtonActionPerformed

    private void ModifyPButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModifyPButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.setVisible(false);
            new MainMenu().setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F11){
            this.setVisible(false);
        ShowSpecserv s = new ShowSpecserv();
        s.setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F12){
            this.setVisible(false);
            Show s = new Show();
            s.setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_LEFT){
            EnterPButton.requestFocus();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.setVisible(false);
            Show s = new Show();
            s.setVisible(true);
        }
    }//GEN-LAST:event_ModifyPButtonKeyPressed

    private void BackRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackRButtonActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_BackRButtonActionPerformed

    private void BackRButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BackRButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.setVisible(false);
            new MainMenu().setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F11){
            this.setVisible(false);
        ShowSpecserv s = new ShowSpecserv();
        s.setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F12){
            this.setVisible(false);
            Show s = new Show();
            s.setVisible(true);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_RIGHT){
            EnterPButton.requestFocus();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            EnterPButton.requestFocus();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            EnterPButton.requestFocus();
        }

    }//GEN-LAST:event_BackRButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackRButton;
    private javax.swing.JButton EnterPButton;
    private javax.swing.JButton ModifyPButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
